language: python

python:
- 2.7

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libpcap-dev libsrtp0-dev

install:
- pip install Cython
- pip install -e .[test]

script:
- py.test test/ --cov dsrtp --cov-report term-missing --pep8
